version: "3"

services:
  db_postgres:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    build: .
    volumes:
      - static:/code/static
      - media:/code/media
      - .:/code
    depends_on:
      - db_postgres
    environment:
      VIRTUAL_HOST: jonathanvazquez.tk

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
      - media:/code/webpersonal/media
    depends_on:
      - django_app

volumes:
  .:
  postgres_data:
  static:
  media: